### ISSUE TITLE
Cannot compile project with nfc1 dependency

### ISSUE THREAD

**Issue by jacopo-degattis** [alexrsagen/rs-usb-compat-01-sys#7] opened 2024-09-27 16:45 UTC
Good evening,
I'm trying to use this library in my rust project, I'm on a mac with arm64 architecture.

When I execute the `cargo build` command I get the following error:

```
  ld: in /Users/lore/Documents/Repos/nfc_reader/target/debug/build/usb-compat-01-sys-3364509719431851/out/libusb.a(libusb.a), archive member 'libusb.a' with length 371440 is not mach-o or llvm bitcode file '/Users/lore/Documents/Repos/nfc_reader/target/debug/build/usb-compat-01-sys-3364509719431851/out/libusb.a' for architecture arm64
  clang: error: linker command failed with exit code 1 (use -v to see invocation)
  make[2]: *** [libnfc/libnfc.6.0.0.dylib] Error 1
  make[1]: *** [libnfc/CMakeFiles/nfc.dir/all] Error 2
  make: *** [all] Error 2
  thread 'main' panicked at /Users/lore/.cargo/registry/src/index.crates.io-6f17d22bba15001f/cmake-0.1.51/src/lib.rs:1100:5:
```

How can I solve this issue ?

Thank you

**Comment by alexrsagen** [comment] 2024-09-30 09:52
`libusb.a` is linked as an object here:

https://github.com/alexrsagen/rs-usb-compat-01-sys/blob/0e878694c0c42fffc586d9a7ca20b340b46ffe0b/build.rs#L42

I should probably change this to link an object file instead of an archive file.

Will give this a try, then test building `usb-compat-01-sys`, `nfc1-sys` and `nfc1` on Apple Silicon.

**Comment by alexrsagen** [comment] 2024-10-01 19:05
Hi @jacopo-degattis,

Could you run the following commands and share the output with me to help diagnose the issue further:

```
cat /Users/lore/Documents/Repos/nfc_reader/target/debug/build/usb-compat-01-sys-3364509719431851/output
tree /Users/lore/Documents/Repos/nfc_reader/target/debug/build/usb-compat-01-sys-3364509719431851/out/
ar -t /Users/lore/Documents/Repos/nfc_reader/target/debug/build/usb-compat-01-sys-3364509719431851/out/libusb.a
```

Thanks!

**Comment by jacopo-degattis** [comment] 2024-10-01 19:18
Hey, 
Thanks for the quick response

Here are the outputs from the commands you wrote:

Command:
```
cat /Users/lore/Documents/Repos/nfc_reader/target/debug/build/usb-compat-01-sys-3364509719431851/output
```

Output:
```
cargo:include=/Users/lore/Documents/Repos/nfc_reader/target/debug/build/usb-compat-01-sys-3364509719431851/out/include
cargo:rerun-if-env-changed=LIBUDEV_NO_PKG_CONFIG
cargo:rerun-if-env-changed=PKG_CONFIG_aarch64-apple-darwin
cargo:rerun-if-env-changed=PKG_CONFIG_aarch64_apple_darwin
cargo:rerun-if-env-changed=HOST_PKG_CONFIG
cargo:rerun-if-env-changed=PKG_CONFIG
cargo:rerun-if-env-changed=LIBUDEV_STATIC
cargo:rerun-if-env-changed=LIBUDEV_DYNAMIC
cargo:rerun-if-env-changed=PKG_CONFIG_ALL_STATIC
cargo:rerun-if-env-changed=PKG_CONFIG_ALL_DYNAMIC
cargo:rerun-if-env-changed=PKG_CONFIG_PATH_aarch64-apple-darwin
cargo:rerun-if-env-changed=PKG_CONFIG_PATH_aarch64_apple_darwin
cargo:rerun-if-env-changed=HOST_PKG_CONFIG_PATH
cargo:rerun-if-env-changed=PKG_CONFIG_PATH
cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR_aarch64-apple-darwin
cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR_aarch64_apple_darwin
cargo:rerun-if-env-changed=HOST_PKG_CONFIG_LIBDIR
cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR
cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR_aarch64-apple-darwin
cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR_aarch64_apple_darwin
cargo:rerun-if-env-changed=HOST_PKG_CONFIG_SYSROOT_DIR
cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR
TARGET = Some(aarch64-apple-darwin)
OPT_LEVEL = Some(0)
HOST = Some(aarch64-apple-darwin)
cargo:rerun-if-env-changed=CC_aarch64-apple-darwin
CC_aarch64-apple-darwin = None
cargo:rerun-if-env-changed=CC_aarch64_apple_darwin
CC_aarch64_apple_darwin = None
cargo:rerun-if-env-changed=HOST_CC
HOST_CC = None
cargo:rerun-if-env-changed=CC
CC = None
cargo:rerun-if-env-changed=CC_ENABLE_DEBUG_OUTPUT
RUSTC_WRAPPER = None
cargo:rerun-if-env-changed=CRATE_CC_NO_DEFAULTS
CRATE_CC_NO_DEFAULTS = None
DEBUG = Some(true)
cargo:rerun-if-env-changed=MACOSX_DEPLOYMENT_TARGET
MACOSX_DEPLOYMENT_TARGET = None
cargo:rerun-if-env-changed=CFLAGS_aarch64-apple-darwin
CFLAGS_aarch64-apple-darwin = None
cargo:rerun-if-env-changed=CFLAGS_aarch64_apple_darwin
CFLAGS_aarch64_apple_darwin = None
cargo:rerun-if-env-changed=HOST_CFLAGS
HOST_CFLAGS = None
cargo:rerun-if-env-changed=CFLAGS
CFLAGS = None
cargo:warning=/Users/lore/.cargo/registry/src/index.crates.io-6f17d22bba15001f/usb-compat-01-sys-0.2.4/vendor/usb-compat-0.1/libusb/core.c:209:4: warning: 'libusb_set_debug' is deprecated [-Wdeprecated-declarations]
cargo:warning=                        libusb_set_debug(ctx, 3);
cargo:warning=                        ^
cargo:warning=/Users/lore/Documents/Repos/nfc_reader/target/debug/build/libusb1-sys-a1d4dbdc1785ac63/out/include/libusb.h:1351:1: note: 'libusb_set_debug' has been explicitly marked deprecated here
cargo:warning=LIBUSB_DEPRECATED_FOR(libusb_set_option)
cargo:warning=^
cargo:warning=/Users/lore/Documents/Repos/nfc_reader/target/debug/build/libusb1-sys-a1d4dbdc1785ac63/out/include/libusb.h:70:50: note: expanded from macro 'LIBUSB_DEPRECATED_FOR'
cargo:warning=#define LIBUSB_DEPRECATED_FOR(f) __attribute__ ((deprecated))
cargo:warning=                                                 ^
cargo:warning=/Users/lore/.cargo/registry/src/index.crates.io-6f17d22bba15001f/usb-compat-01-sys-0.2.4/vendor/usb-compat-0.1/libusb/core.c:219:3: warning: 'libusb_set_debug' is deprecated [-Wdeprecated-declarations]
cargo:warning=                libusb_set_debug(ctx, 3);
cargo:warning=                ^
cargo:warning=/Users/lore/Documents/Repos/nfc_reader/target/debug/build/libusb1-sys-a1d4dbdc1785ac63/out/include/libusb.h:1351:1: note: 'libusb_set_debug' has been explicitly marked deprecated here
cargo:warning=LIBUSB_DEPRECATED_FOR(libusb_set_option)
cargo:warning=^
cargo:warning=/Users/lore/Documents/Repos/nfc_reader/target/debug/build/libusb1-sys-a1d4dbdc1785ac63/out/include/libusb.h:70:50: note: expanded from macro 'LIBUSB_DEPRECATED_FOR'
cargo:warning=#define LIBUSB_DEPRECATED_FOR(f) __attribute__ ((deprecated))
cargo:warning=                                                 ^
cargo:warning=/Users/lore/.cargo/registry/src/index.crates.io-6f17d22bba15001f/usb-compat-01-sys-0.2.4/vendor/usb-compat-0.1/libusb/core.c:811:51: warning: passing 'char *' to parameter of type 'unsigned char *' converts between pointers to integer types where one is of the unique plain 'char' type and the other is not [-Wpointer-sign]
cargo:warning=        r = libusb_bulk_transfer(dev->handle, ep & 0xff, bytes, size,
cargo:warning=                                                         ^~~~~
cargo:warning=/Users/lore/Documents/Repos/nfc_reader/target/debug/build/libusb1-sys-a1d4dbdc1785ac63/out/include/libusb.h:1800:41: note: passing argument to parameter 'data' here
cargo:warning=        unsigned char endpoint, unsigned char *data, int length,
cargo:warning=                                               ^
cargo:warning=/Users/lore/.cargo/registry/src/index.crates.io-6f17d22bba15001f/usb-compat-01-sys-0.2.4/vendor/usb-compat-0.1/libusb/core.c:856:56: warning: passing 'char *' to parameter of type 'unsigned char *' converts between pointers to integer types where one is of the unique plain 'char' type and the other is not [-Wpointer-sign]
cargo:warning=        r = libusb_interrupt_transfer(dev->handle, ep & 0xff, bytes, size,
cargo:warning=                                                              ^~~~~
cargo:warning=/Users/lore/Documents/Repos/nfc_reader/target/debug/build/libusb1-sys-a1d4dbdc1785ac63/out/include/libusb.h:1804:41: note: passing argument to parameter 'data' here
cargo:warning=        unsigned char endpoint, unsigned char *data, int length,
cargo:warning=                                               ^
cargo:warning=/Users/lore/.cargo/registry/src/index.crates.io-6f17d22bba15001f/usb-compat-01-sys-0.2.4/vendor/usb-compat-0.1/libusb/core.c:902:54: warning: passing 'char *' to parameter of type 'unsigned char *' converts between pointers to integer types where one is of the unique plain 'char' type and the other is not [-Wpointer-sign]
cargo:warning=                bRequest & 0xff, wValue & 0xffff, wIndex & 0xffff, bytes, size & 0xffff,
cargo:warning=                                                                   ^~~~~
cargo:warning=/Users/lore/Documents/Repos/nfc_reader/target/debug/build/libusb1-sys-a1d4dbdc1785ac63/out/include/libusb.h:1797:17: note: passing argument to parameter 'data' here
cargo:warning=        unsigned char *data, uint16_t wLength, unsigned int timeout);
cargo:warning=                       ^
cargo:warning=/Users/lore/.cargo/registry/src/index.crates.io-6f17d22bba15001f/usb-compat-01-sys-0.2.4/vendor/usb-compat-0.1/libusb/core.c:916:20: warning: passing 'char *' to parameter of type 'unsigned char *' converts between pointers to integer types where one is of the unique plain 'char' type and the other is not [-Wpointer-sign]
cargo:warning=                langid & 0xffff, buf, (int) buflen);
cargo:warning=                                 ^~~
cargo:warning=/Users/lore/Documents/Repos/nfc_reader/target/debug/build/libusb1-sys-a1d4dbdc1785ac63/out/include/libusb.h:1842:54: note: passing argument to parameter 'data' here
cargo:warning=        uint8_t desc_index, uint16_t langid, unsigned char *data, int length)
cargo:warning=                                                            ^
cargo:warning=/Users/lore/.cargo/registry/src/index.crates.io-6f17d22bba15001f/usb-compat-01-sys-0.2.4/vendor/usb-compat-0.1/libusb/core.c:927:3: warning: passing 'char *' to parameter of type 'unsigned char *' converts between pointers to integer types where one is of the unique plain 'char' type and the other is not [-Wpointer-sign]
cargo:warning=                buf, (int) buflen);
cargo:warning=                ^~~
cargo:warning=/Users/lore/Documents/Repos/nfc_reader/target/debug/build/libusb1-sys-a1d4dbdc1785ac63/out/include/libusb.h:1850:37: note: passing argument to parameter 'data' here
cargo:warning=        uint8_t desc_index, unsigned char *data, int length);
cargo:warning=                                           ^
cargo:warning=7 warnings generated.
cargo:rerun-if-env-changed=AR_aarch64-apple-darwin
AR_aarch64-apple-darwin = None
cargo:rerun-if-env-changed=AR_aarch64_apple_darwin
AR_aarch64_apple_darwin = None
cargo:rerun-if-env-changed=HOST_AR
HOST_AR = None
cargo:rerun-if-env-changed=AR
AR = None
cargo:rerun-if-env-changed=ARFLAGS_aarch64-apple-darwin
ARFLAGS_aarch64-apple-darwin = None
cargo:rerun-if-env-changed=ARFLAGS_aarch64_apple_darwin
ARFLAGS_aarch64_apple_darwin = None
cargo:rerun-if-env-changed=HOST_ARFLAGS
HOST_ARFLAGS = None
cargo:rerun-if-env-changed=ARFLAGS
ARFLAGS = None
cargo:rustc-link-lib=static=usb
cargo:rustc-link-search=native=/Users/lore/Documents/Repos/nfc_reader/target/debug/build/usb-compat-01-sys-3364509719431851/out
cargo:vendored=1
cargo:static=1
cargo:include=/Users/lore/Documents/Repos/nfc_reader/target/debug/build/usb-compat-01-sys-3364509719431851/out/include
cargo:version_number=0.1.7
cargo:rustc-link-lib=framework=CoreFoundation
cargo:rustc-link-lib=framework=IOKit
cargo:rustc-link-lib=objc
cargo:rerun-if-env-changed=LIBUDEV_NO_PKG_CONFIG
cargo:rerun-if-env-changed=PKG_CONFIG_aarch64-apple-darwin
cargo:rerun-if-env-changed=PKG_CONFIG_aarch64_apple_darwin
cargo:rerun-if-env-changed=HOST_PKG_CONFIG
cargo:rerun-if-env-changed=PKG_CONFIG
cargo:rerun-if-env-changed=LIBUDEV_STATIC
cargo:rerun-if-env-changed=LIBUDEV_DYNAMIC
cargo:rerun-if-env-changed=PKG_CONFIG_ALL_STATIC
cargo:rerun-if-env-changed=PKG_CONFIG_ALL_DYNAMIC
cargo:rerun-if-env-changed=PKG_CONFIG_PATH_aarch64-apple-darwin
cargo:rerun-if-env-changed=PKG_CONFIG_PATH_aarch64_apple_darwin
cargo:rerun-if-env-changed=HOST_PKG_CONFIG_PATH
cargo:rerun-if-env-changed=PKG_CONFIG_PATH
cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR_aarch64-apple-darwin
cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR_aarch64_apple_darwin
cargo:rerun-if-env-changed=HOST_PKG_CONFIG_LIBDIR
cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR
cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR_aarch64-apple-darwin
cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR_aarch64_apple_darwin
cargo:rerun-if-env-changed=HOST_PKG_CONFIG_SYSROOT_DIR
cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR
```

Command:
```
tree /Users/lore/Documents/Repos/nfc_reader/target/debug/build/usb-compat-01-sys-3364509719431851/out/
```

Output:
```
/Users/lore/Documents/Repos/nfc_reader/target/debug/build/usb-compat-01-sys-3364509719431851/out/
├── bindings.rs
├── c4e542ee6893d701-core.o
├── include
│   ├── config.h
│   ├── lusb0_usb.h
│   └── usb.h
└── libusb.a

2 directories, 6 files
```

Command:
```
ar -t /Users/lore/Documents/Repos/nfc_reader/target/debug/build/usb-compat-01-sys-3364509719431851/out/libusb.a
```

Output:
```
__.SYMDEF SORTED
c4e542ee6893d701-core.o
libusb.a
```

Thanks !!

**Comment by alexrsagen** [comment] 2024-10-01 20:55
Please let me know if the issue is resolved in `v0.2.6`, @jacopo-degattis 😄

**Closed as completed** 2024-10-01 20:54 UTC

**Comment by jacopo-degattis** [comment] 2024-10-02 08:03
Yes it do solved the compilation error and now everything compiles as it should but when i try to execute this code

```rust
fn main() -> nfc1::Result<()> {
    println!("libnfc v{}", nfc1::version());

    let mut context = nfc1::Context::new()?;
    let mut device = context.open()?;

    println!(
        "NFC device {:?} opened through connection {:?}",
        device.name(),
        device.connstring()
    );
    println!(
        "- Initiator modulations: {:?}",
        device.get_supported_modulation(nfc1::Mode::Initiator)?
    );
    println!(
        "- Target modulations: {:?}",
        device.get_supported_modulation(nfc1::Mode::Target)?
    );

    Ok(())
}
```

It throws me this error:
```
error: linking with `cc` failed: exit status: 1
  |
  = note: env -u IPHONEOS_DEPLOYMENT_TARGET -u TVOS_DEPLOYMENT_TARGET -u XROS_DEPLOYMENT_TARGET LC_ALL="C" PATH="/Users/jack/.rustup/toolchains/stable-aarch64-apple-darwin/lib/rustlib/aarch64-apple-darwin/bin:/Users/jack/Documents/miniconda3/bin:/Users/jack/.bun/bin:/Users/jack/.pyenv/shims:/Users/jack/.pyenv/bin:/Users/jack/Library/pnpm:/Users/jack/.nvm/versions/node/v18.12.1/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/Library/Apple/usr/bin:/Users/jack/.cargo/bin:/Users/jack/Library/Android/sdk/emulator:/Users/jack/Library/Android/sdk/tools:/Users/jack/Library/Android/sdk/tools/bin:/Users/jack/Library/Android/sdk/platform-tools:/Users/jack/Library/Android/sdk/build-tools/30.0.3/:/Users/jack/Library/Flutter/bin:/Users/jack/Scripts/:/opt/homebrew/Cellar/ifuse-mac/1.1.4.reinstall/bin:/Users/jack/.flutter-spy" VSLANG="1033" ZERO_AR_DATE="1" "cc" "-arch" "arm64" "/var/folders/h7/dbx4tw496tl7qfxnjyh06nq00000gn/T/rustcIdt5t0/symbols.o" "/Users/jack/Documents/Repositories/nfc_reader/target/debug/deps/nfc_reader-dd1528951753ed0e.18ej7sm2hjmlcrj.rcgu.o" "/Users/jack/Documents/Repositories/nfc_reader/target/debug/deps/nfc_reader-dd1528951753ed0e.33jdaalnnumchuj8.rcgu.o" "/Users/jack/Documents/Repositories/nfc_reader/target/debug/deps/nfc_reader-dd1528951753ed0e.3cp1nls4cbaj1829.rcgu.o" "/Users/jack/Documents/Repositories/nfc_reader/target/debug/deps/nfc_reader-dd1528951753ed0e.3j23ddfa6rj92qzd.rcgu.o" "/Users/jack/Documents/Repositories/nfc_reader/target/debug/deps/nfc_reader-dd1528951753ed0e.3zsovrvewzontttg.rcgu.o" "/Users/jack/Documents/Repositories/nfc_reader/target/debug/deps/nfc_reader-dd1528951753ed0e.4fsal8jgilkleif6.rcgu.o" "/Users/jack/Documents/Repositories/nfc_reader/target/debug/deps/nfc_reader-dd1528951753ed0e.4lg41o4qhewnknu.rcgu.o" "/Users/jack/Documents/Repositories/nfc_reader/target/debug/deps/nfc_reader-dd1528951753ed0e.517zh8hsxcdo7kii.rcgu.o" "/Users/jack/Documents/Repositories/nfc_reader/target/debug/deps/nfc_reader-dd1528951753ed0e.bcjikfj8yu5duw2.rcgu.o" "/Users/jack/Documents/Repositories/nfc_reader/target/debug/deps/nfc_reader-dd1528951753ed0e.x0rzlpnhyft4g7z.rcgu.o" "/Users/jack/Documents/Repositories/nfc_reader/target/debug/deps/nfc_reader-dd1528951753ed0e.4tv69fri9m3pmazi.rcgu.o" "-L" "/Users/jack/Documents/Repositories/nfc_reader/target/debug/deps" "-L" "/usr/local/include" "-L" "/usr/local/lib" "-L" "/Users/jack/Documents/Repositories/nfc_reader/target/debug/build/nfc1-sys-d046b2563086aa17/out/build/libnfc" "-L" "/Users/jack/Documents/Repositories/nfc_reader/target/debug/build/libusb1-sys-9f683bdcf23466cf/out" "-L" "/Users/jack/Documents/Repositories/nfc_reader/target/debug/build/usb-compat-01-sys-84e6dd86cec31a33/out" "-L" "/Users/jack/.rustup/toolchains/stable-aarch64-apple-darwin/lib/rustlib/aarch64-apple-darwin/lib" "/Users/jack/Documents/Repositories/nfc_reader/target/debug/deps/libnfc1-89b40e102f5ca446.rlib" "/Users/jack/Documents/Repositories/nfc_reader/target/debug/deps/libnfc1_sys-a55b4276b36610c4.rlib" "/Users/jack/.rustup/toolchains/stable-aarch64-apple-darwin/lib/rustlib/aarch64-apple-darwin/lib/libstd-7f95fd207255b41e.rlib" "/Users/jack/.rustup/toolchains/stable-aarch64-apple-darwin/lib/rustlib/aarch64-apple-darwin/lib/libpanic_unwind-97393370543e3207.rlib" "/Users/jack/.rustup/toolchains/stable-aarch64-apple-darwin/lib/rustlib/aarch64-apple-darwin/lib/libobject-a3d7c43b176960f9.rlib" "/Users/jack/.rustup/toolchains/stable-aarch64-apple-darwin/lib/rustlib/aarch64-apple-darwin/lib/libmemchr-6371ee3a4bb27ae4.rlib" "/Users/jack/.rustup/toolchains/stable-aarch64-apple-darwin/lib/rustlib/aarch64-apple-darwin/lib/libaddr2line-a7cf1a11761951bf.rlib" "/Users/jack/.rustup/toolchains/stable-aarch64-apple-darwin/lib/rustlib/aarch64-apple-darwin/lib/libgimli-dad018a8d4ef8593.rlib" "/Users/jack/.rustup/toolchains/stable-aarch64-apple-darwin/lib/rustlib/aarch64-apple-darwin/lib/librustc_demangle-913776ff724458d1.rlib" "/Users/jack/.rustup/toolchains/stable-aarch64-apple-darwin/lib/rustlib/aarch64-apple-darwin/lib/libstd_detect-364b04ba0ead75b3.rlib" "/Users/jack/.rustup/toolchains/stable-aarch64-apple-darwin/lib/rustlib/aarch64-apple-darwin/lib/libhashbrown-918cdfbdd32cf1d1.rlib" "/Users/jack/.rustup/toolchains/stable-aarch64-apple-darwin/lib/rustlib/aarch64-apple-darwin/lib/librustc_std_workspace_alloc-424311e8ba1b9112.rlib" "/Users/jack/.rustup/toolchains/stable-aarch64-apple-darwin/lib/rustlib/aarch64-apple-darwin/lib/libminiz_oxide-d4352744eff98311.rlib" "/Users/jack/.rustup/toolchains/stable-aarch64-apple-darwin/lib/rustlib/aarch64-apple-darwin/lib/libadler-dd9df5b2170395b8.rlib" "/Users/jack/.rustup/toolchains/stable-aarch64-apple-darwin/lib/rustlib/aarch64-apple-darwin/lib/libunwind-6b98b9caf95b8907.rlib" "/Users/jack/.rustup/toolchains/stable-aarch64-apple-darwin/lib/rustlib/aarch64-apple-darwin/lib/libcfg_if-d4913584d9013c52.rlib" "/Users/jack/.rustup/toolchains/stable-aarch64-apple-darwin/lib/rustlib/aarch64-apple-darwin/lib/liblibc-04f062133e43a7ac.rlib" "/Users/jack/.rustup/toolchains/stable-aarch64-apple-darwin/lib/rustlib/aarch64-apple-darwin/lib/liballoc-5397ff6f88f2713a.rlib" "/Users/jack/.rustup/toolchains/stable-aarch64-apple-darwin/lib/rustlib/aarch64-apple-darwin/lib/librustc_std_workspace_core-5142793ba4eb4c05.rlib" "/Users/jack/.rustup/toolchains/stable-aarch64-apple-darwin/lib/rustlib/aarch64-apple-darwin/lib/libcore-24a1e099f55e6f0d.rlib" "/Users/jack/.rustup/toolchains/stable-aarch64-apple-darwin/lib/rustlib/aarch64-apple-darwin/lib/libcompiler_builtins-9ca5cbf9e98b80b9.rlib" "-framework" "CoreFoundation" "-framework" "IOKit" "-lobjc" "-lSystem" "-lc" "-lm" "-L" "/Users/jack/.rustup/toolchains/stable-aarch64-apple-darwin/lib/rustlib/aarch64-apple-darwin/lib" "-o" "/Users/jack/Documents/Repositories/nfc_reader/target/debug/deps/nfc_reader-dd1528951753ed0e" "-Wl,-dead_strip" "-nodefaultlibs"
  = note: Undefined symbols for architecture arm64:
            "_usb_bulk_read", referenced from:
                _acr122_usb_bulk_read in libnfc1_sys-a55b4276b36610c4.rlib[18](libnfcdrivers_la-acr122_usb.o)
                _pn53x_usb_bulk_read in libnfc1_sys-a55b4276b36610c4.rlib[22](libnfcdrivers_la-pn53x_usb.o)
            "_usb_bulk_write", referenced from:
                _acr122_usb_bulk_write in libnfc1_sys-a55b4276b36610c4.rlib[18](libnfcdrivers_la-acr122_usb.o)
                _acr122_usb_bulk_write in libnfc1_sys-a55b4276b36610c4.rlib[18](libnfcdrivers_la-acr122_usb.o)
                _pn53x_usb_bulk_write in libnfc1_sys-a55b4276b36610c4.rlib[22](libnfcdrivers_la-pn53x_usb.o)
                _pn53x_usb_bulk_write in libnfc1_sys-a55b4276b36610c4.rlib[22](libnfcdrivers_la-pn53x_usb.o)
            "_usb_claim_interface", referenced from:
                _acr122_usb_open in libnfc1_sys-a55b4276b36610c4.rlib[18](libnfcdrivers_la-acr122_usb.o)
                _pn53x_usb_open in libnfc1_sys-a55b4276b36610c4.rlib[22](libnfcdrivers_la-pn53x_usb.o)
            "_usb_close", referenced from:
                _acr122_usb_scan in libnfc1_sys-a55b4276b36610c4.rlib[18](libnfcdrivers_la-acr122_usb.o)
                _acr122_usb_scan in libnfc1_sys-a55b4276b36610c4.rlib[18](libnfcdrivers_la-acr122_usb.o)
                _acr122_usb_scan in libnfc1_sys-a55b4276b36610c4.rlib[18](libnfcdrivers_la-acr122_usb.o)
                _acr122_usb_open in libnfc1_sys-a55b4276b36610c4.rlib[18](libnfcdrivers_la-acr122_usb.o)
                _acr122_usb_open in libnfc1_sys-a55b4276b36610c4.rlib[18](libnfcdrivers_la-acr122_usb.o)
                _acr122_usb_close in libnfc1_sys-a55b4276b36610c4.rlib[18](libnfcdrivers_la-acr122_usb.o)
                _pn53x_usb_scan in libnfc1_sys-a55b4276b36610c4.rlib[22](libnfcdrivers_la-pn53x_usb.o)
                _pn53x_usb_scan in libnfc1_sys-a55b4276b36610c4.rlib[22](libnfcdrivers_la-pn53x_usb.o)
                ...
            "_usb_find_busses", referenced from:
                _usb_prepare in libnfc1_sys-a55b4276b36610c4.rlib[17](libnfcbuses_la-usbbus.o)
            "_usb_find_devices", referenced from:
                _usb_prepare in libnfc1_sys-a55b4276b36610c4.rlib[17](libnfcbuses_la-usbbus.o)
            "_usb_get_busses", referenced from:
                _acr122_usb_scan in libnfc1_sys-a55b4276b36610c4.rlib[18](libnfcdrivers_la-acr122_usb.o)
                _acr122_usb_open in libnfc1_sys-a55b4276b36610c4.rlib[18](libnfcdrivers_la-acr122_usb.o)
                _pn53x_usb_scan in libnfc1_sys-a55b4276b36610c4.rlib[22](libnfcdrivers_la-pn53x_usb.o)
                _pn53x_usb_open in libnfc1_sys-a55b4276b36610c4.rlib[22](libnfcdrivers_la-pn53x_usb.o)
            "_usb_get_string_simple", referenced from:
                _acr122_usb_open in libnfc1_sys-a55b4276b36610c4.rlib[18](libnfcdrivers_la-acr122_usb.o)
                _acr122_usb_open in libnfc1_sys-a55b4276b36610c4.rlib[18](libnfcdrivers_la-acr122_usb.o)
                _pn53x_usb_get_usb_device_name in libnfc1_sys-a55b4276b36610c4.rlib[22](libnfcdrivers_la-pn53x_usb.o)
                _pn53x_usb_get_usb_device_name in libnfc1_sys-a55b4276b36610c4.rlib[22](libnfcdrivers_la-pn53x_usb.o)
            "_usb_init", referenced from:
                _usb_prepare in libnfc1_sys-a55b4276b36610c4.rlib[17](libnfcbuses_la-usbbus.o)
            "_usb_open", referenced from:
                _acr122_usb_scan in libnfc1_sys-a55b4276b36610c4.rlib[18](libnfcdrivers_la-acr122_usb.o)
                _acr122_usb_scan in libnfc1_sys-a55b4276b36610c4.rlib[18](libnfcdrivers_la-acr122_usb.o)
                _acr122_usb_scan in libnfc1_sys-a55b4276b36610c4.rlib[18](libnfcdrivers_la-acr122_usb.o)
                _acr122_usb_open in libnfc1_sys-a55b4276b36610c4.rlib[18](libnfcdrivers_la-acr122_usb.o)
                _pn53x_usb_scan in libnfc1_sys-a55b4276b36610c4.rlib[22](libnfcdrivers_la-pn53x_usb.o)
                _pn53x_usb_open in libnfc1_sys-a55b4276b36610c4.rlib[22](libnfcdrivers_la-pn53x_usb.o)
            "_usb_release_interface", referenced from:
                _acr122_usb_close in libnfc1_sys-a55b4276b36610c4.rlib[18](libnfcdrivers_la-acr122_usb.o)
                _pn53x_usb_close in libnfc1_sys-a55b4276b36610c4.rlib[22](libnfcdrivers_la-pn53x_usb.o)
            "_usb_reset", referenced from:
                _acr122_usb_open in libnfc1_sys-a55b4276b36610c4.rlib[18](libnfcdrivers_la-acr122_usb.o)
            "_usb_set_altinterface", referenced from:
                _acr122_usb_open in libnfc1_sys-a55b4276b36610c4.rlib[18](libnfcdrivers_la-acr122_usb.o)
            "_usb_set_configuration", referenced from:
                _pn53x_usb_scan in libnfc1_sys-a55b4276b36610c4.rlib[22](libnfcdrivers_la-pn53x_usb.o)
                _pn53x_usb_open in libnfc1_sys-a55b4276b36610c4.rlib[22](libnfcdrivers_la-pn53x_usb.o)
          ld: symbol(s) not found for architecture arm64
          clang: error: linker command failed with exit code 1 (use -v to see invocation)
          

warning: `nfc_reader` (bin "nfc_reader") generated 2 warnings
error: could not compile `nfc_reader` (bin "nfc_reader") due to 1 previous error; 2 warnings emitted
```

I noticed that if I only use the `nfc1::version()` it works perfectly but any other function lead me to the error above.

Thanks again
Jacopo

**Comment by alexrsagen** [comment] 2024-10-02 13:59
Hi, I was able to reproduce the issue on a MacBook Air with Apple Silicon, running a clean install of macOS 15 Sequoia.

I made some changes to https://github.com/alexrsagen/libnfc in order to compile LibNFC statically (so that LibUSB can be statically linked, as was always intended). The problem should be resolved now.

The following commands were used to build and confirm that it is working:
```
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
export PATH="/opt/homebrew/bin:$PATH" >> ~/.zshenv
brew install rustup
brew install cmake
brew install pkg-config
rustup update stable
rustup-init
git clone https://github.com/alexrsagen/rs-nfc1-sys.git
cd rs-nfc1-sys
git submodule update --init --recursive
cargo run --example list_readers
```

Please give `nfc1-sys` `v0.3.9` a try and let me know if it works @jacopo-degattis 😄
